name: wilobu_app
description: Aplicación móvil Wilobu
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '^3.10.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0

  firebase_core: ^3.4.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/wilobu_logo.png
    - assets/images/fondo_wilobu.jpg
